image: cr.yandex/crp742p3qacifd2hcon2/practice-da:latest

stages:
    - init
    - run

test_report_job:
    stage: run
    only:
        - schedules
    script:
        - pip install statsmodels
        - python 05.alert-wip.py
