image: cr.yandex/crp742p3qacifd2hcon2/practice-da:latest

stages:
    - init
    - run

installing_dependencies:
    stage: init
    only:
        - schedules
    script:
        - pip install statsmodels

test_report_job:
    stage: run
    only:
        - schedules
    script:
        - python 05.alert-wip.py
